# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, deployment, deployment_status]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  show-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
